// BB Cards data — 4 sets × 32 cards.
// Each card: n (number), en (English), jp (Japanese), id (Google Drive mp3 file id)
// Audio is streamed from Google Drive: https://drive.google.com/uc?export=download&id=<id>
window.SETS = {
  diamond: {
    mark: "♦", name: "BB Cards ① ダイヤ", color: "#e0457b", prefix: "d",
    cards: [
      { n: 1,  en: `Betty Botter bought some butter.`, jp: `ベティーボターちゃんはバターを買いました。`, id: `1yY8gVPPafLRM80kfGFKQzhghLI6gtazV` },
      { n: 2,  en: `Cathay Carter comes to school.`, jp: `キャシーカーターちゃんは学校へ来ます。`, id: `1LAfXDpI3AaL-o4bTQEtABXshpwM-P3Pb` },
      { n: 3,  en: `Mr. Celery lives in the city.`, jp: `セロリーさんは町に住んでいます。`, id: `1BPC2kW6Tp5ONZKksKid6s9fZazgORXja` },
      { n: 4,  en: `Dolly Dimple danced with a dog.`, jp: `ドーリーディンプルちゃんは犬とダンスをしました。`, id: `1NbZbvaA4e_dPeUPGG9sYn0i6z7tKJiyK` },
      { n: 5,  en: `The flying fish will get to the forest.`, jp: `とんでいる魚は森につくでしょう。`, id: `1ysy_D51t6irFY1xPDSXrzL_Ul1QwHVdW` },
      { n: 6,  en: `Gray Goose got some golden eggs.`, jp: `グレイグースさんは金の卵を手に入れました。`, id: `1IXKVh5qhckZY3k40Lv59QN1GOv8GNZjG` },
      { n: 7,  en: `Gentel Giraffe looks at George.`, jp: `ジェントルジラフさんがジョージを見ています。`, id: `1VDJbZysaxf64doO-Kneo3T7ZSjSmxIlF` },
      { n: 8,  en: `Happy Henry has gone to Hawaii.`, jp: `ハッピーヘンリーさんはハワイへ行ってしまいました。`, id: `1kcFhzzwsWLQ45F1uqXF31nJxA3kLjusD` },
      { n: 9,  en: `Jack and Jill jumped into the jet.`, jp: `ジャックくんとジルちゃんは飛行機にとび乗りました。`, id: `1fQL9MLzZYQDx1UL_DkMC737XoaI8uKGT` },
      { n: 10, en: `Ken and Kate keep me waiting.`, jp: `ケンくんとケイトちゃんは私をまたせます。`, id: `1YCexc_SjDM1GZuJAXKFHbUmanB6ynKDw` },
      { n: 11, en: `Lucy Locket lost her letter.`, jp: `ルーシーロケットちゃんは手紙をなくしました。`, id: `1b0thzbPtDiH6_5a4AiUpdgcixpSta8hy` },
      { n: 12, en: `Mad Monkey made a lot of money.`, jp: `マッドマンキーさんはお金をたくさんもうけました。`, id: `1lWA5pNaC246GpzE33NaiKL0t7mSU5ES0` },
      { n: 13, en: `Nancy gave me nine new nails.`, jp: `ナンシーちゃんは私に新しいくぎを9本くれました。`, id: `1lzCXldNejvT-1uGF2XQUqpeu_E2tDWXu` },
      { n: 14, en: `Peter piper peeled a pink peach.`, jp: `ピーターパイパーくんはピンク色のももの皮をむきました。`, id: `1qNEohL6r9epqSjWFQrfi3umUYVm1xU1a` },
      { n: 15, en: `The queen gives a quiet party.`, jp: `その女王様は静かなパーティーを開きます。`, id: `1QNLGMVyjyhaiIdJyjHU7p30ri7VpNPw2` },
      { n: 16, en: `Red rooster will finish reading.`, jp: `レッドルースターさんは本を読み終わります。`, id: `11NBbmSwaRvkiinUhGYOrJ3pGuglK4r1c` },
      { n: 17, en: `Betty Botter bought some butter for her mother.`, jp: `（お母さんに）`, id: `1yTKGQB6FiZDhpm2R8yfp2ZXahOw6_s7A` },
      { n: 18, en: `Cathay Carter comes to school on foot.`, jp: `（歩いて）`, id: `1wopHnAtouXYAWTboTaIREBKGQd-bF0A9` },
      { n: 19, en: `Mr. Celery lives in the city with his friends.`, jp: `（友達と一緒に）`, id: `1Icm_vc8b6QZqN-nzhLZhhrImvpmQRsVW` },
      { n: 20, en: `Dolly Dimple danced with a dog for five hours.`, jp: `（5時間）`, id: `1YAV7J3e8ZNYpaGze-xkTm3oSUtrK6Lo0` },
      { n: 21, en: `The flying fish will get to the forest by four.`, jp: `（4時までに）`, id: `1dBlYcvby4WD2MtkZuq2fsbupx9rRVLRw` },
      { n: 22, en: `Gray Goose got some golden eggs very quickly.`, jp: `（素早く）`, id: `1P4Mgtzwh3TLKhuIOPK7YPZMezKit96vY` },
      { n: 23, en: `Gentel Giraffe looks at George with a smile.`, jp: `（微笑んで）`, id: `1W3c-tzgyiMwcV46JtePZY0T1UK4N4BNq` },
      { n: 24, en: `Happy Henry has gone to Hawaii to meet his parents.`, jp: `（両親に会いに）`, id: `13Ib2sdubNtj-TVZS8u08Ad-7MN-yJSqr` },
      { n: 25, en: `Jack and Jill jumped into the jet in a hurry.`, jp: `（急いで）`, id: `14LPv1fsTLsRKfkHRjZNJgPaloPI-m9O3` },
      { n: 26, en: `Ken and Kate keep me waiting all the time.`, jp: `（いつも）`, id: `1FBGsb8bqxWJHjdwzjL3sBG66zcF8hXDq` },
      { n: 27, en: `Lucy Locket lost her letter last month.`, jp: `（先月）`, id: `196NA6S3bBa4rAMrBko7lVOsuLveiLdw2` },
      { n: 28, en: `Mad Monkey made a lot of money in many ways.`, jp: `（色々な方法で）`, id: `1DSyreUObBiaJEFUroiqkmCPGQZrRpMDN` },
      { n: 29, en: `Nancy gave me nine new nails for nothing.`, jp: `（無料で）`, id: `10EnlQJ3g0a0_ru7FhHcyh48FWN3HvD1P` },
      { n: 30, en: `Peter piper peeled a pink peach this morning.`, jp: `（今朝）`, id: `1FXi59Zbl38FoyInQ20PDHHWSxNk3mf3P` },
      { n: 31, en: `The queen gives a quiet party every other week.`, jp: `（1週間おきに）`, id: `19Gky96vXbQZZurA6C2KCgLS5gaBbOIRx` },
      { n: 32, en: `Red rooster will finish reading before long.`, jp: `（間もなく）`, id: `1hKUuUOeKMFIzjxnMD8GZStejPZ377gWy` }
    ]
  },
  heart: {
    mark: "♥", name: "BB Cards ② ハート", color: "#e0457b", prefix: "h",
    cards: [
      { n: 1,  en: `Sister Susie sipped spicy soup.`, jp: `スージー姉さんはぴりっとしたスープを少しずつ飲みました。`, id: `1CtHJatHtDfVi50QSnBfhiFBilJvVd_Ya` },
      { n: 2,  en: `Mr. Frog sells apples and bananas.`, jp: `フロッグさんはりんごとバナナを売ります。`, id: `1YDMGFC7REjMJFjivbyvrKrITh3UkFCK4` },
      { n: 3,  en: `Tommy Tucker took a train.`, jp: `トミータッカーさんは電車に乗りました。`, id: `1YN3Yvn_Ob3OJXMUovfc54K8y3G5ZyBgE` },
      { n: 4,  en: `Victor the violinist visits the village.`, jp: `バイオリンひきのビクターさんはその村をおとずれます。`, id: `1QmVKqPABUt0Aox-wgimhNEvBiknzg-LU` },
      { n: 5,  en: `Willy doesn't want to get wet.`, jp: `ウィリーくんはぬれたくありません。`, id: `1uoASkzhU8wZYBZM47k1uBffCIZgGpRfr` },
      { n: 6,  en: `Mr. Fox got out of a taxi.`, jp: `フォックスさんはタクシーを降りました。`, id: `1MWLWvUBCI8GsUeFAaTHvgQy1fpJJNr9n` },
      { n: 7,  en: `Yacht is younger than Boat.`, jp: `ヨットくんはボートくんより若いです。`, id: `1hCJhbWsA8ZGDRb8CMYXTd2YXfDGHZOAE` },
      { n: 8,  en: `Mr. Zebra came from Zanzibar.`, jp: `ゼブラさんはザンジバルから来ました。`, id: `1m7xPizbRh1l9DcP2c2rrBMHk1ugNGbnL` },
      { n: 9,  en: `Charlie Champion went to China.`, jp: `チャーリーチャンピオンさんは中国へ行きました。`, id: `1WZTeR9crOEauf87AHIcO97BKloBYP0Rs` },
      { n: 10, en: `The tough guy couldn't stop laughing.`, jp: `タフな男のひとは笑いが止まりませんでした。`, id: `19ceyR3SqqIdsh-Z4QuAoCg4Fylu5TGHf` },
      { n: 11, en: `The young singer didn't sing.`, jp: `若い歌手は歌をうたいませんでした。`, id: `15jRLfKFMPgty4gMzhjx1oxZxCHubdi90` },
      { n: 12, en: `Dolphin and Elephant talked over the phone.`, jp: `ドルフィンくんとエレファントくんは電話で話をしました。`, id: `19kkyHIH8xn7gEyjHoKJ_QidvJQ_lUuKu` },
      { n: 13, en: `Ship and Sheep went shopping.`, jp: `シップくんとシープさんは買い物に行きました。`, id: `1QZu_zngyNaRad08pCUx9evHCqNEU3UKI` },
      { n: 14, en: `Dr. Smith got thirty-three thin thermometers.`, jp: `スミス博士は細い体温計を33本うけとりました。`, id: `19rUCO3oibZu0a8NnOzwStXrxMxZPnAjg` },
      { n: 15, en: `These are the stamps that Father got.`, jp: `これはお父さんが買った切手です。`, id: `1BEF9t0zUO96zc-q_q2xH-EEf8qBoTzzm` },
      { n: 16, en: `Mr. Whitney was drinking something white.`, jp: `ホイットニーさんは何か白いものを飲んでいました。`, id: `1drMUDXkfbzhevA0zJVGNV2343P79eKs9` },
      { n: 17, en: `Sister Susie sipped spicy soup for supper.`, jp: `（夕食に）`, id: `1g9eO8O37UDHerAUUY2sAouF2k3NjlHuK` },
      { n: 18, en: `Mr. Frog sells apples and bananas on his way home.`, jp: `（家に帰る途中）`, id: `1JU8AVD5is6fJv7neKcGn_Cq0ew4sQ6C5` },
      { n: 19, en: `Tommy Tucker took a train a few minutes ago.`, jp: `（2、3分前に）`, id: `1-xrVW1h00wu-dVSFNBvKeUgbnymaSfFl` },
      { n: 20, en: `Victor the violinist visits the village every day.`, jp: `（毎日）`, id: `1VFYIjDhTs8YSGpIq3rVg7PUGr-9uJn4r` },
      { n: 21, en: `Willy doesn't want to get wet on Wednesday.`, jp: `（水曜日は）`, id: `1dgaJZ7byetM7w4IfOhiDgAzIP7XstMms` },
      { n: 22, en: `Mr. Fox got out of a taxi at the gate.`, jp: `（門のところで）`, id: `1QMegh3Dg63ZM-PHN_r812Oa5de9ZrHcD` },
      { n: 23, en: `Yacht is younger than Boat by ten years.`, jp: `（10歳）`, id: `1hmkaZx1o2Hi8AoJS1FF6ndk42dKrhWtU` },
      { n: 24, en: `Mr. Zebra came from Zanzibar by zeppelin.`, jp: `（飛行船で）`, id: `1e8E3GYJLn3b_gfHZXigae84ixMlNhFl7` },
      { n: 25, en: `Charlie Champion went to China on business.`, jp: `（仕事で）`, id: `1A-pyv4sifaDxc3xnA_P-6VIEg36R9-nx` },
      { n: 26, en: `The tough guy couldn't stop laughing all day long.`, jp: `（1日中）`, id: `1Y2-xP-jBrJWF2hMYImMyW7l7id6MareA` },
      { n: 27, en: `The young singer didn't sing on the street.`, jp: `（街角で）`, id: `1EYm75xnAp17l2-ALSisWazb4Ct5S_tdJ` },
      { n: 28, en: `Dolphin and Elephant talked over the phone to each other.`, jp: `（お互いに）`, id: `1e3Ue5FR9FLYaRJHyIyO6F8yynBB_szF5` },
      { n: 29, en: `Ship and Sheep went shopping in the afternoon.`, jp: `（午後）`, id: `1JK6Sa_nM2xSKvJrlZEL5i5jmR-yp_zL5` },
      { n: 30, en: `Dr. Smith got thirty-three thin thermometers yesterday afternoon.`, jp: `（昨日の午後）`, id: `1bN5yuT0QbCVFYrRGdj-tXfFCDMe146If` },
      { n: 31, en: `These are the stamps that Father got at the shop.`, jp: `（店で）`, id: `1XXC3_9c1mY4zlcR29a1YINZzuOJhG-a7` },
      { n: 32, en: `Mr. Whitney was drinking something white over there.`, jp: `（あそこで）`, id: `1rOHZYRHtvFb6c6SCePKDcS2_RPfGiTf5` }
    ]
  },
  clover: {
    mark: "♣", name: "BB Cards ③ クローバー", color: "#2f9e44", prefix: "c",
    cards: [
      { n: 1,  en: `The cat in the hat has a pan.`, jp: `ぼうしをかぶった猫はフライパンを持っています。`, id: `1wgWClraTlJMOONhSYJFLP6prEttaGNDW` },
      { n: 2,  en: `Eddy will send me ten red hens.`, jp: `エディくんは私に赤いめん鳥を10羽送ってくれます。`, id: `1VzzvbjPC9-IWmIKnTC0bmRMXvs55ndgF` },
      { n: 3,  en: `Six little kittens sit in a row.`, jp: `6匹の小さな子猫が1列にすわっています。`, id: `1zjydE0ep2V81EZzBuXWkMVQxI-olTZMF` },
      { n: 4,  en: `The clock on the rock received a shock.`, jp: `岩の上の時計はショックを受けました。`, id: `18mDCmPUsBR2LSDLpz59nAxOl0ckihSWw` },
      { n: 5,  en: `Mrs. Monkey won a large sum of money.`, jp: `モンキー夫人はたくさんのお金を勝ちとりました。`, id: `14BfvjkHXM6DZCfrzUZcmvSrSuPZgrcMW` },
      { n: 6,  en: `The ugly umbrella is unhappy.`, jp: `みにくいカサはみじめです。`, id: `1g_4lG8rTFDc__hxgOPntK0rQelO93vVA` },
      { n: 7,  en: `Mr. Lake bakes a cake.`, jp: `レイクさんはケーキを焼きます。`, id: `1w8CfATJxirsKutRbbZXrtoZ9dMZkq_ot` },
      { n: 8,  en: `Daisy was waiting for the train.`, jp: `デイジーちゃんは電車を待っていました。`, id: `1OMUJ5XK2dRTJonxVNRqUOemxqKfPTPlX` },
      { n: 9,  en: `Jay stayed at the Pumpkin Hotel.`, jp: `ジェイさんはパンプキンホテルに泊まりました。`, id: `1mUmclEtMd1K7-SNpE63DVraacIKWvurK` },
      { n: 10, en: `Miss Peach eats four meals.`, jp: `ピーチさんは4回食事をします。`, id: `1IKSaAFm8BFdv0Ad8KUnamgqaL_Dh9eN9` },
      { n: 11, en: `Bee can see three green trees.`, jp: `ビーくんは緑の木が3本みえます。`, id: `1iw9v5lN2Rt9_bwAawBGR-ODROQw06BDd` },
      { n: 12, en: `Mike likes to write letters.`, jp: `マイクくんは手紙を書くのが好きです。`, id: `1kmAvgeflT40azYr9mJC3uns3K5mtqwLf` },
      { n: 13, en: `The bright boy had a light meal.`, jp: `頭のよい少年は軽く食事をしました。`, id: `1YCJ3DWzZT0RTubhXhM8K0qX_6ksh4jgJ` },
      { n: 14, en: `Why does the spy dry his pants.`, jp: `なぜスパイはズボンを干すのですか。`, id: `18JO-1hOm3JLfrTkDfAa2m9vTbRabH7KL` },
      { n: 15, en: `A mule was playing with a tube.`, jp: `ラバがチューブで遊んでいました。`, id: `1nwZsJl0c95DeDO8si62s1gbfEkvjmBCu` },
      { n: 16, en: `The gold made the old man happy.`, jp: `金（きん）がおじいさんをしあわせにしました。`, id: `1hVwIR-oJJl3tfNqTqY9w-GuMQFiaLSbi` },
      { n: 17, en: `The cat in the hat has a pan in her hands.`, jp: `（手に）`, id: `1f1NWcrnQ6S-fRIvlKlnK9sd8LrvcWksV` },
      { n: 18, en: `Eddy will send me ten red hens tomorrow morning.`, jp: `（明日の朝）`, id: `1-ay65M4PoP5yLxCZUzb9ZEkasWqodauk` },
      { n: 19, en: `Six little kittens sit in a row by the window.`, jp: `（窓際で）`, id: `1i1F6P-OiiJjJNo0jyecIrqiYdu2kfL9L` },
      { n: 20, en: `The clock on the rock received a shock at last.`, jp: `（ついに）`, id: `1I9Fgh3kO9mKtPPR94WcWX53P8O5DKXoE` },
      { n: 21, en: `Mrs. Monkey won a large sum of money in London.`, jp: `（ロンドンで）`, id: `11297mX3o7QdJMr8U5y7eWH3dTmFbriOO` },
      { n: 22, en: `The ugly umbrella is unhappy on a fine day.`, jp: `（晴れた日は）`, id: `1iUmwjquWJdMHjH_npWYccbOdkEmFFfxS` },
      { n: 23, en: `Mr. Lake bakes a cake twice a day.`, jp: `（一日に二度）`, id: `1VppraekdFl_NtHyToGFShcOiEGchdb6Z` },
      { n: 24, en: `Daisy was waiting for the train in the rain.`, jp: `（雨の中で）`, id: `1EthZ6u7rG6NtXmo0RdY-nysB2Gcrn3Rm` },
      { n: 25, en: `Jay stayed at the Pumpkin Hotel for a few days.`, jp: `（2～3日）`, id: `1-KfRJIVb_oNFJd2clVLDadiGsNbl6Tkr` },
      { n: 26, en: `Miss Peach eats four meals a day.`, jp: `（1日に）`, id: `1Dlm9xL3xXTkZNquDV1Z2m5c4NUEXAFnd` },
      { n: 27, en: `Bee can see three green trees far away.`, jp: `（遠くに）`, id: `1r26YPpiia0oa4zo2gats6jXaMuWONDMM` },
      { n: 28, en: `Mike likes to write letters in Japanese.`, jp: `（日本語で）`, id: `1Ypar9g65hKBYInmKjXGPRQRSRev-N4Ic` },
      { n: 29, en: `The bright boy had a light meal at seven.`, jp: `（7時に）`, id: `1K-q15c6HpavSYrWNQtnt8reJnkRxzlDa` },
      { n: 30, en: `Why does the spy dry his pants in the sun?`, jp: `（日向で）`, id: `1FJB6lapOgOQfTQQrlPMLr9VI9EXuNqlk` },
      { n: 31, en: `A mule was playing with a tube on the field.`, jp: `（野原で）`, id: `1Pez1yWZJYp0yUI6gGBeFfeahsVE9vkcw` },
      { n: 32, en: `The gold made the old man happy for a while.`, jp: `（しばらくの間）`, id: `1CFpw1NkipoAWbUt0zwxCG_9DIDwYQkxd` }
    ]
  },
  spade: {
    mark: "♠", name: "BB Cards ④ スペード", color: "#343a40", prefix: "s",
    cards: [
      { n: 1,  en: `Ms. Goat toasted a bar of soap.`, jp: `ゴートさんは石鹸をトーストしました。`, id: `1G90JL6fWE6nx98n_LygViCGA2FdUVZBf` },
      { n: 2,  en: `Rosy Rose drove me home.`, jp: `ロージーローズさんは私を家まで車で送ってくれました。`, id: `1Ka2bnYB9OLCZlv5MZpr5ChgYQ5yaiwCz` },
      { n: 3,  en: `A crow in yellow showed me a rainbow.`, jp: `黄色い服を着たカラスが私に虹を見せてくれました。`, id: `1NLIQB7_9v_ATFQEUVcDIQtuGvr-QFgg_` },
      { n: 4,  en: `A Woodchuck looked for a good cookbook.`, jp: `ウッドチャックがよい料理の本をさがしていました。`, id: `1vvQHSmgHVD0QtrVgSAOymMFNA4F3ozTp` },
      { n: 5,  en: `It was too cool to go to the swimming pool.`, jp: `涼しすぎてプールに行けませんでした。`, id: `1KxpxVUS7Cc7pfHDuQ1T_BvfW3tsD8SfC` },
      { n: 6,  en: `A group of children made tomato soup.`, jp: `子どもたちのグループがトマトスープを作りました。`, id: `1hd5RAJO3oTSH22b8V5tQR_59goDYKjW0` },
      { n: 7,  en: `The mouse found no house.`, jp: `ねずみは家が見つかりませんでした。`, id: `11zXjGaIu8FUELjPomenuQmovrNAFmB0O` },
      { n: 8,  en: `The young couple was in the country.`, jp: `若いカップルは田舎にいました。`, id: `1fud_phlUi7dID-R1kVrF0rZ8BK0CgaIJ` },
      { n: 9,  en: `The small dog is called "Paul".`, jp: `小さな犬はポールと呼ばれています。`, id: `1j1rxJXgi6AgWV_3ReEzzvGm-xSwF9nCa` },
      { n: 10, en: `It is getting warmer and warmer.`, jp: `だんだん暖かくなってきます。`, id: `1CLZbGednhGhLRNzqI1iQgni1S8mmxAs7` },
      { n: 11, en: `The daughter likes August the best.`, jp: `その娘は8月がいちばん好きです。`, id: `1zt5XS9buCSmLOJsdwhfO95IRWnGas67K` },
      { n: 12, en: `The woman thought, then bought the dress.`, jp: `女の人は考えて、そのドレスを買いました。`, id: `1G4YR5kFlqbYbraTTU-05dU28ZIwvEYuM` },
      { n: 13, en: `The early bird heard a word.`, jp: `早起き鳥は話し声を聞きました。`, id: `16Be1d_alIFps2iSXyQAgEb8vWqdSFxAv` },
      { n: 14, en: `The girl is washing a dirty bird.`, jp: `女の子が汚れた鳥を洗っています。`, id: `14oDbuPIVT5TOVxUlvmkPr-Zrb05popQe` },
      { n: 15, en: `Lazy Worm worked hard.`, jp: `レイジーワームさんは一生けんめいに働きました。`, id: `1QTJUwhXhbEsSvPPUCNRnb9wAKn5c2P3P` },
      { n: 16, en: `Dr. Turtle will return home.`, jp: `タートル博士は家に戻ります。`, id: `1LgV7lp3-JWr0qeF2kldUqH24JAgZXcj9` },
      { n: 17, en: `Ms. Goat toasted a bar of soap by mistake.`, jp: `（間違えて）`, id: `14mobICmp0JNQSFUyDtfk0jZzNFUbw3yu` },
      { n: 18, en: `Rosy Rose drove me home before lunch.`, jp: `（お昼ご飯の前に）`, id: `1LHWVzh87Uyr1UAsPJHe5H91aeAdPZj1P` },
      { n: 19, en: `A crow in yellow showed me a rainbow over the river.`, jp: `（川の上の）`, id: `1xKf9fng5YKZFS0yJKA5PW28zL2FQzqZp` },
      { n: 20, en: `A Woodchuck looked for a good cookbook for a long time.`, jp: `（長い間）`, id: `1WHSvqruqrwttTgmsf103-k7HP51jggBZ` },
      { n: 21, en: `It was too cool to go to the swimming pool the day before yesterday.`, jp: `（一昨日）`, id: `1budlgWStE8bDHh3KwzHzZuHHwRVBVsI_` },
      { n: 22, en: `A group of children made tomato soup in the kitchen.`, jp: `（台所で）`, id: `1tWlOpCQjnD1sSb6LUzIOwMtclBYk2Sza` },
      { n: 23, en: `The mouse found no house to live in.`, jp: `（住む）`, id: `1zp2UO7sl1u0AJwWM4o_3n6KDfvJNuIax` },
      { n: 24, en: `The young couple was in the country last Monday.`, jp: `（この前の月曜日）`, id: `1yKE08K_FncpY3Ezn_rWfUWZSA5N4X5vS` },
      { n: 25, en: `The small dog is called "Paul" by everyone.`, jp: `（みんなに）`, id: `1LbYQwFzEZq9TELk3K-BoH-P7uq2T3Iv1` },
      { n: 26, en: `It is getting warmer and warmer in spring.`, jp: `（春には）`, id: `1XoRCkkd_DWp4BJqFSprSxYR64camcpfB` },
      { n: 27, en: `The daughter likes August the best out of the year.`, jp: `（一年のうちで）`, id: `17xGpKX_HlWllki5jWn17yWbA65dmXyLx` },
      { n: 28, en: `The woman thought, then bought the dress for fifty dollars.`, jp: `（50ドルで）`, id: `1Stsib4yzIIfY7EUzIwZHYDsVaZVjgXW2` },
      { n: 29, en: `The early bird heard a word in the dark.`, jp: `（暗闇で）`, id: `1FM8NsfnQwguHvovUGEVJ0lhNccJ1GQ0v` },
      { n: 30, en: `The girl is washing a dirty bird with difficulty.`, jp: `（苦労して）`, id: `1Cci8UWPNDsAYjD0oWIQ1EfW-b2UPPkUR` },
      { n: 31, en: `Lazy Worm worked hard for the first time.`, jp: `（初めて）`, id: `1TtwvRNswn88StizwQd6cXpAbE5S8uGIx` },
      { n: 32, en: `Dr. Turtle will return home in a few days.`, jp: `（2、3日すれば）`, id: `1rgokhez-sOqZ1frPDkigfKfb7cfa_yPZ` }
    ]
  }
};
